# Generated by Django 6.0.1 on 2026-02-07 05:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organization_organizationmembership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('description_fr', models.CharField(blank=True, max_length=500, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('authorize_url', models.URLField(blank=True, max_length=500, null=True)),
                ('redirect_url', models.URLField(blank=True, max_length=500, null=True)),
                ('token_url', models.URLField(blank=True, max_length=500, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_post', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integration.platform')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(blank=True, max_length=500, null=True)),
                ('access_token_secret', models.CharField(blank=True, max_length=500, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('platform_type', models.CharField(choices=[('user', 'User'), ('page', 'Page')], max_length=100)),
                ('reconnection', models.BooleanField(db_index=True, default=False)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('external_name', models.CharField(blank=True, max_length=255, null=True)),
                ('external_profile_picture', models.ImageField(blank=True, null=True, upload_to='user_platform/profile/')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.platform')),
            ],
        ),
    ]
