# Generated by Django 6.0.1 on 2026-02-07 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='organization name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10, verbose_name='role')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_memberships', to=settings.AUTH_USER_MODEL, verbose_name='invited by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.organization', verbose_name='organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'organization membership',
                'verbose_name_plural': 'organization memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='organizations', through='accounts.OrganizationMembership', through_fields=('organization', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='business name')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='accounts.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'business',
                'verbose_name_plural': 'businesses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='accounts_bu_organiz_c7f6f8_idx')],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'organization'], name='accounts_or_user_id_0c79eb_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'role'], name='accounts_or_organiz_eae39b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('user', 'organization')},
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['owner', 'is_active'], name='accounts_or_owner_i_b0770a_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='accounts_or_slug_7a4a7c_idx'),
        ),
    ]
